name: Build and Deploy to GitHub Pages (v3)

on:
  # push:
  #   branches:
  #     - master

  workflow_dispatch:

#: ++++++++++++++++++++++++++++++++++++++++++
permissions:
  contents: write  # Wymagane do pusha na gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      - name: Setup Node.js (with pnpm)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          # cache: 'pnpm' # opcjonalnie: cache dla szybszych instalacji

      - name: Install pnpm (jeśli setup-node nie wystarczy)
        run: npm install -g pnpm

      - name: Install dependencies
        # run: pnpm install
        run: pnpm install --no-frozen-lockfile

      # - name: Prebuild (copy files cache)
      #   run: pnpm run prebuild

      - name: Build Astro
        run: pnpm run build

      # - name: Postbuild (restore files)
      #   run: pnpm run postbuild

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatycznie dostępny
          publish_branch: gh-pages  # Docelowa gałąź
          publish_dir: ./dist       # Folder z plikami
          # Opcjonalne dodatkowe ustawienia:
          # user_name: 'GitHub Actions'
          # user_email: 'actions@github.com'
          # commit_message: 'Deploy: gh-pages'
