name: Build and Deploy to GitHub Pages (v3)

on:
  # push:
  #   branches:
  #     - master

  workflow_dispatch:

#: ++++++++++++++++++++++++++++++++++++++++++
permissions:
  contents: write  # Wymagane do pusha na gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      - name: Setup Node.js (with pnpm)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          # cache: 'pnpm' # opcjonalnie: cache dla szybszych instalacji

      - name: Install pnpm (jeśli setup-node nie wystarczy)
        run: npm install -g pnpm

      - name: Install dependencies
        # run: pnpm install
        run: pnpm install --no-frozen-lockfile

      # - name: Prebuild (copy files cache)
      #   run: pnpm run prebuild

      - name: Build Astro
        run: pnpm run build

      # - name: Postbuild (restore files)
      #   run: pnpm run postbuild

      - name: "Add CNAME for: veriKami/www-sauerland-astro"
        if: github.repository == 'veriKami/www-sauerland-astro'
        run: echo "gh.sauerland.pl" > ./dist/CNAME

      - name: "Remove CNAME for: profesorus/profesorus.github.io"
        if: github.repository == 'profesorus/profesorus.github.io'
        run: |
          if [ -f ./dist/CNAME ]; then
            rm ./dist/CNAME
            echo "Usunięto CNAME dla repo: ${{ github.repository }}"
          else
            echo "Plik CNAME nie istnieje, pomijam."
          fi

      # - name: Delete CNAME if matches repo
      #   if: github.repository == 'veriKami/temporary-site'
      #   run: rm -f ./dist/CNAME

      # - name: Remove CNAME for multiple repos
      #   if: contains('veriKami/repo1 veriKami/repo2', github.repository)
      #   run: rm -f ./dist/CNAME

      # - name: Create CNAME only if not exists
      #   run: |
      #     if [ ! -f ./dist/CNAME ]; then
      #       echo "www.${GITHUB_REPOSITORY#*/}.example.com" > ./dist/CNAME
      #     fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatycznie dostępny
          publish_branch: gh-pages  # Docelowa gałąź
          publish_dir: ./dist       # Folder z plikami
          # Opcjonalne dodatkowe ustawienia:
          # user_name: 'GitHub Actions'
          # user_email: 'actions@github.com'
          # commit_message: 'Deploy: gh-pages'
